# Site settings
title: "Xerus"
baseurl: "" # the subpath of your site, e.g. /blog/
port: 4002
url: "http://localhost:4002" # the base hostname & protocol for your site

# Conversion
markdown: kramdown
